<a href="https://colab.research.google.com/github/4dh/networkFlowOptimization_public/blob/master/DNAsequencing_KruskalsAlg_PrimsAlg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Danielle Heymann

CSCI 688: Network Optimization

**Homework 8 Programs**

In [ ]:
import networkx as nx
import csv
import numpy as np


**Problem 2: Kruskal's, Prim's, and DNA**

In [ ]:
# Given DNA sequences
DNAs = [[0,0,0,0,0,0,0,1,0,1],
        [1,1,0,0,1,1,1,1,1,1],
        [1,1,0,0,1,1,1,1,1,0], 
        [0,0,0,0,0,0,1,0,0,1],
        [0,0,0,0,1,1,1,1,1,1]]

# table to show amount of flips between 2 sequences
Flips = np.zeros((5,5))

# variable i to got through each row for DNA sequence corresponding to one list element- which is another list- in DNAs
for i in DNAs:
  # flip count variable
  # another variable r to go through each row to compare to i's 1's and 0's
  for r in DNAs:
    flipcount = 0
    # another counter p to go through each element in DNA sequences that we compare
    for p in range(10):
      if r[p] != i[p]:
        flipcount += 1
      
      Flips[DNAs.index(i)][DNAs.index(r)] = flipcount

# neat table for flips from sequences
# note that it is symmetric over diagonal and diagonal is 0 which 
# is expected as there are no flips from sequence i, to itself, sequence i
for i in Flips:
  print(i)


[0. 6. 7. 2. 4.]
[6. 0. 1. 6. 2.]
[7. 1. 0. 7. 3.]
[2. 6. 7. 0. 4.]
[4. 2. 3. 4. 0.]


In [ ]:
# Now I am storing flip values from the right top diagonal for edge cost between nodes
costs = []
cost= []

for i in range(0,5):
  #print(i)
  for k in range((i+1),5):
    costs.append([('node i', i+1),('node j', k+1), ('cost', (Flips[i,k])), ('is in MST','no')])
    cost.append([i+1, k+1, (Flips[i,k])])
for i in costs:
  print(i)
for i in cost:
  print(i)

[('node i', 1), ('node j', 2), ('cost', 6.0), ('is in MST', 'no')]
[('node i', 1), ('node j', 3), ('cost', 7.0), ('is in MST', 'no')]
[('node i', 1), ('node j', 4), ('cost', 2.0), ('is in MST', 'no')]
[('node i', 1), ('node j', 5), ('cost', 4.0), ('is in MST', 'no')]
[('node i', 2), ('node j', 3), ('cost', 1.0), ('is in MST', 'no')]
[('node i', 2), ('node j', 4), ('cost', 6.0), ('is in MST', 'no')]
[('node i', 2), ('node j', 5), ('cost', 2.0), ('is in MST', 'no')]
[('node i', 3), ('node j', 4), ('cost', 7.0), ('is in MST', 'no')]
[('node i', 3), ('node j', 5), ('cost', 3.0), ('is in MST', 'no')]
[('node i', 4), ('node j', 5), ('cost', 4.0), ('is in MST', 'no')]
[1, 2, 6.0]
[1, 3, 7.0]
[1, 4, 2.0]
[1, 5, 4.0]
[2, 3, 1.0]
[2, 4, 6.0]
[2, 5, 2.0]
[3, 4, 7.0]
[3, 5, 3.0]
[4, 5, 4.0]


For Kruskal's algorithm, we start with T= an empty set of edges. Here, I will sort edges in order of increasing edge cost and add each edge in (without creating a cycle to keep this a tree). I will sort the edges according to cost, and then I will add each edge into the solution set (while making sure that for each edge that I add, the number of edges in the tree is equal to n-1, where n is the number of unique nodes in the current tree.

In [ ]:
sortedcosts = sorted(costs, key=lambda elem: elem[2])
for i in sortedcosts:
  print(i)

sortedcost = sorted(cost, key=lambda elem: elem[2])
for i in sortedcost:
  print(i)

nodes04 = sortedcost[0:9]


[('node i', 2), ('node j', 3), ('cost', 1.0), ('is in MST', 'no')]
[('node i', 1), ('node j', 4), ('cost', 2.0), ('is in MST', 'no')]
[('node i', 2), ('node j', 5), ('cost', 2.0), ('is in MST', 'no')]
[('node i', 3), ('node j', 5), ('cost', 3.0), ('is in MST', 'no')]
[('node i', 1), ('node j', 5), ('cost', 4.0), ('is in MST', 'no')]
[('node i', 4), ('node j', 5), ('cost', 4.0), ('is in MST', 'no')]
[('node i', 1), ('node j', 2), ('cost', 6.0), ('is in MST', 'no')]
[('node i', 2), ('node j', 4), ('cost', 6.0), ('is in MST', 'no')]
[('node i', 1), ('node j', 3), ('cost', 7.0), ('is in MST', 'no')]
[('node i', 3), ('node j', 4), ('cost', 7.0), ('is in MST', 'no')]
[2, 3, 1.0]
[1, 4, 2.0]
[2, 5, 2.0]
[3, 5, 3.0]
[1, 5, 4.0]
[4, 5, 4.0]
[1, 2, 6.0]
[2, 4, 6.0]
[1, 3, 7.0]
[3, 4, 7.0]


In [ ]:
#T is the solution set
T = []

#for simplicity of indexing and node names, I am making the node values from 0-4 instead of 1-5
for i in range(len(nodes04)):
  nodes04[i][0] -= 1
  nodes04[i][1] -= 1

print(nodes04)

[[1, 2, 1.0], [0, 3, 2.0], [1, 4, 2.0], [2, 4, 3.0], [0, 4, 4.0], [3, 4, 4.0], [0, 1, 6.0], [1, 3, 6.0], [0, 2, 7.0]]


In [ ]:
T = []
#friends are any predecessors of a node
friends = [['.'],['.'],['.'],['.'],['.']]
#value of 1 if the node is in solution set and 0 if not)
indicator = [0,0,0,0,0]
#for i in range

#add first edge to MST
T.append(nodes04[0])

i = nodes04[0][0]
j = nodes04[0][1]
indicator[i] = 1
indicator[j] = 1

if i not in friends[j]:
  friends[j].append(i)
if j not in friends[i]:
  friends[i].append(j)

nodesum = 2
for r in range(1, len(nodes04)):
  i = nodes04[r][0]
  j = nodes04[r][1]
  found = False

  for q in range(len(friends)):
    if ((i in friends[q]) and (j in friends[q])):
      found = True

  if (len(T) < nodesum) and ((i not in friends[j]) or (j not in friends[i])) and (found == False):
  
    T.append(nodes04[r])
    indicator[i] = 1
    indicator[j] = 1
    nodesum = sum(indicator)

    # i and j are now friends
    if i not in friends[j]:
      friends[j].append(i)
    # share i's friends with j
    for y in friends[i]:
      if y not in friends[j]:
        friends[j].append(y)

    #j and i are no friends
    if j not in friends[i]:
      friends[i].append(j)
    #share j's friends with i
    for z in friends[j]:
      if z not in friends[i]:
        friends[i].append(z)

for i in range(len(friends)):
  print(i)
  print(friends[i])

#cost calculation
costtotal1 = 0
for i in range(len(T)):
  if i < len(T):
    ni1 = T[i][0]
    nj1 = T[i][1]
    cninj1 = Flips[ni1][nj1]
    costtotal1 = costtotal1 +cninj1

print("")
print('___________SOLUTION FOR MST___(using Kruskals alg)_________')
print(T)
print("cost: ", costtotal1)


0
['.', 3, 0, 4, 1, 2]
1
['.', 2, 4, 1]
2
['.', 1]
3
['.', 0]
4
['.', 1, 2, 0, 3]

___________SOLUTION FOR MST___(using Kruskals alg)_________
[[1, 2, 1.0], [0, 3, 2.0], [1, 4, 2.0], [0, 4, 4.0]]
cost:  9.0


Prim's Algorithm

In [ ]:
# I will recycle the edge cost matrix from previous work, and will be using nodes04prim array 
# to retrieve costs between nodes when needed.

#edges list witg costs to look at adjacent nodes of what we are working with
print(nodes04)
edgelistprims = sorted(nodes04, key=lambda ele: ele[2])

# node list for node and weight
#initial distance is infinity to the nodes that are not the first node we choose
initialnodedistance = [(0,0),(1,float('inf')),(2,float('inf')),(3,float('inf')),(4,float('inf'))]


solution = []
pathcost = []

#node-cost pair list to keep and update
nodecostpairs = sorted(initialnodedistance, key=lambda ele: ele[1])

#this one we will pop the first value from, so it will decrease until all nodes are in solution
nodesNOTinS = [0,1,2,3,4]

#look at every node in the list of edges to see if the distance from the node we are on
#has shorter distance to neighbors than we already know of
#for e in nodes04prims:
counter_a = 0

for i in range(5): 
  switch = False
  #explored_node has attributes (node, distance)
  
  explored_node = nodecostpairs[counter_a]

  #if counter_a == 0:
    #we have nothing in solution and we are on starting node- need to add this 
    
    #solution.append(explored_node[0])
    #popped = nodecostpairsNOTinS.pop()
    #print(popped)

  for t in edgelistprims:
      #t has attributes (node i, node j, cost)
      #find neighbors of the current node we are exploring
      #need to look to see which node is the neighbor and which is the current explored in the edge
    if (t[0] == explored_node[0]):
      #found neighbor
      #update costs of neighbors
      neighbor = t[1]

      if neighbor not in solution:
        #nodecostpairs has attributes (node, cost/distance)
        #compare t[2], the edge's cost, to the current cost value for node in stored nodecostpairs
        if nodecostpairs[neighbor][1] > t[2]:
         
          nodecostpairs.pop(neighbor)
          nodecostpairs.append((neighbor, t[2]))
          nodecostpairs = sorted(nodecostpairs, key=lambda ele: ele[0])
          #nodecostpairs[neighbor][1] = t[2]
          
    if (t[1] == explored_node[0]):
      #found neighbor
      #update costs of neighbors if the 
      neighbor = t[0]
      if neighbor not in solution:
        if nodecostpairs[neighbor][1] > t[2]:
         
          nodecostpairs.pop(neighbor)
          nodecostpairs.append((neighbor, t[2]))
          nodecostpairs = sorted(nodecostpairs, key=lambda ele: ele[0])
          #nodecostpairs[neighbor][1] = t[2]
       
  if len(solution) < 5: 
    
   
    #new node to expolore is the min distance in the list of nodes not in S

    
    #add min cost node to solution
    
    if len(nodesNOTinS) > 0 :
      
      mincostnode = nodesNOTinS[0]
      for a in nodesNOTinS:
        if nodecostpairs[a][1] < nodecostpairs[mincostnode][1]:
          mincostnode = a
          
      counter_a = mincostnode
  
    solution.append(counter_a)
    nodesNOTinS.remove(counter_a)

  solutionedges = []
  for i in range(len(solution)):
    if i < (len(solution)-1):
      solutionedges.append((solution[i], solution[i+1]))
  
  #cost calculation
  costtotal2 = 0
  for i in range(len(solution)):
    if i < (len(solution)-1):
      ni = solution[i]
      nj = solution[i+1]
      cninj = Flips[ni][nj]
      costtotal2 = costtotal2 +cninj

print("")
print("____________Prims Algorithm Solution___________")
print(solution, solutionedges, "cost", costtotal2)


[[1, 2, 1.0], [0, 3, 2.0], [1, 4, 2.0], [2, 4, 3.0], [0, 4, 4.0], [3, 4, 4.0], [0, 1, 6.0], [1, 3, 6.0], [0, 2, 7.0]]

____________Prims Algorithm Solution___________
[0, 3, 4, 1, 2] [(0, 3), (3, 4), (4, 1), (1, 2)] cost 9.0


Kruskal's and Prim's yield same cost of 9; different solutions because edge costs are not all unique